TARGET = iphone:clang:latest:7.0
INSTALL_TARGET_PROCESSES = theos

include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = theos

theos_FILES = AppDelegate.swift
theos_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
